on:
  pull_request:

  push:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  with-env:
    name: test without deployment environment
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - run: npm install jwt-decode
      - uses: actions/github-script@v7
        with:
          script: |
            const {jwtDecode} = require('jwt-decode')
            const id_token = await core.getIDToken()
            console.log(jwtDecode(id_token)) 

